// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.util;

public class Passable<T> {
	private T value;

	public Passable(T value) {
		this.value = value;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public T getValue() {
		return this.value;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setValue(final T value) {
		this.value = value;
	}
}
