// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.types.steamid;

public class BitVector64 {
	private Long data;

	public BitVector64() {
	}

	public BitVector64(long value) {
		data = value;
	}

	public long getMask(short bitoffset, long valuemask) {
		return (data >> bitoffset) & valuemask;
	}

	public void setMask(short bitoffset, long valuemask, long value) {
		data = (data & ~(valuemask << bitoffset)) | ((value & valuemask) << bitoffset);
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Long getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setData(final Long data) {
		this.data = data;
	}
}
