// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr;

import uk.co.thomasc.steamkit.types.JobID;
import uk.co.thomasc.steamkit.util.logging.Debug;
import uk.co.thomasc.steamkit.util.stream.BinaryReader;

/**
 * This callback is received when a job related operation on the backend has
 * completed, or a client operation should begin.
 *
 * @param <T>
 * The inner callback this job represents.
 */
public final class JobCallback<T extends CallbackMsg> extends BaseJobCallback {
	/**
	 * Gets the inner callback message for this job.
	 */
	private final T callback;

	public JobCallback(JobID jobId, T callback) {
		super(jobId.getValue());
		Debug.Assert(jobId.getValue() != BinaryReader.LongMaxValue, "JobCallback used for non job based callback!");
		callbackType = callback.getClass();
		this.callback = callback;
	}

	/**
	 * Gets the inner callback message for this job.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public T getCallback() {
		return this.callback;
	}
}
