// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamuser.callbacks;

import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver.CMsgClientWalletInfoUpdate;
import uk.co.thomasc.steamkit.base.generated.steamlanguage.ECurrencyCode;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is recieved when wallet info is recieved from the network.
 */
public final class WalletInfoCallback extends CallbackMsg {
	/**
	 * Gets a value indicating whether this instance has wallet data.
	 */
	private final boolean hasWallet;
	/**
	 * Gets the currency code for this wallet.
	 */
	private final ECurrencyCode currency;
	/**
	 * Gets the balance of the wallet, in cents.
	 */
	private final int balance;

	public WalletInfoCallback(CMsgClientWalletInfoUpdate wallet) {
		hasWallet = wallet.hasWallet;
		currency = ECurrencyCode.f(wallet.currency);
		balance = wallet.balance;
	}

	/**
	 * Gets a value indicating whether this instance has wallet data.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isHasWallet() {
		return this.hasWallet;
	}

	/**
	 * Gets the currency code for this wallet.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public ECurrencyCode getCurrency() {
		return this.currency;
	}

	/**
	 * Gets the balance of the wallet, in cents.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getBalance() {
		return this.balance;
	}
}
