// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.callbacks;

import java.util.ArrayList;
import java.util.List;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver2.CMsgCREEnumeratePublishedFilesResponse;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver2.CMsgCREEnumeratePublishedFilesResponse.PublishedFileId;
import uk.co.thomasc.steamkit.base.generated.steamlanguage.EResult;
import uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.SteamWorkshop;
import uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.types.EnumerationDetails;
import uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.types.FileInfo;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is received in response to calling
 * {@link SteamWorkshop#enumeratePublishedFiles(EnumerationDetails)}.
 */
public final class PublishedFilesCallback extends CallbackMsg {
	/**
	 * Gets the result.
	 */
	private final EResult result;
	/**
	 * Gets the list of enumerated files.
	 */
	private final List<FileInfo> files = new ArrayList<FileInfo>();
	/**
	 * Gets the count of total results.
	 */
	private final int totalResults;

	public PublishedFilesCallback(CMsgCREEnumeratePublishedFilesResponse msg) {
		result = EResult.f(msg.eresult);
		for (final PublishedFileId file : msg.publishedFiles) {
			files.add(new FileInfo(file));
		}
		totalResults = msg.totalResults;
	}

	/**
	 * Gets the result.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public EResult getResult() {
		return this.result;
	}

	/**
	 * Gets the list of enumerated files.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<FileInfo> getFiles() {
		return this.files;
	}

	/**
	 * Gets the count of total results.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getTotalResults() {
		return this.totalResults;
	}
}
