// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.types;

import java.util.Date;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver2.CMsgClientUCMEnumerateUserSubscribedFilesResponse;

/**
 * Represents the details of a single published file.
 */
public class FileSubscribed extends File {
	/**
	 * Gets the time this file was subscribed to.
	 */
	private final Date timeSubscribed;

	public FileSubscribed(CMsgClientUCMEnumerateUserSubscribedFilesResponse.PublishedFileId file) {
		super(file.publishedFileId);
		timeSubscribed = new Date(file.rtime32Subscribed);
	}

	/**
	 * Gets the time this file was subscribed to.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Date getTimeSubscribed() {
		return this.timeSubscribed;
	}
}
