// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamworkshop.types;

import java.util.Date;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver2.CMsgClientUCMEnumeratePublishedFilesByUserActionResponse;

/**
 * Represents the details of a single published file.
 */
public class FilePublished extends File {
	/**
	 * Gets the timestamp of this file.
	 */
	private final Date timeStamp;

	public FilePublished(CMsgClientUCMEnumeratePublishedFilesByUserActionResponse.PublishedFileId file) {
		super(file.publishedFileId);
		timeStamp = new Date(file.rtimeTimeStamp);
	}

	/**
	 * Gets the timestamp of this file.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Date getTimeStamp() {
		return this.timeStamp;
	}
}
