// Generated by delombok at Wed Jun 15 22:04:52 CDT 2016
package uk.co.thomasc.steamkit.base;

import java.io.IOException;
import uk.co.thomasc.steamkit.base.generated.steamlanguage.EMsg;
import uk.co.thomasc.steamkit.base.generated.steamlanguageinternal.MsgHdrProtoBuf;
import uk.co.thomasc.steamkit.util.stream.BinaryReader;

/**
 * Represents a protobuf backed packet message.
 */
public final class PacketClientMsgProtobuf implements IPacketMsg {
	/**
	 * This type of message is always protobuf backed.
	 */
	@Override
	public boolean isProto() {
		return true;
	}

	/**
	 * The message type.
	 */
	private EMsg msgType;
	private final long targetJobID;
	private final long sourceJobID;
	byte[] payload;

	/**
	 * Initializes a new instance of the {@link PacketClientMsgProtobuf} class.
	 *
	 * @param eMsg
	 * The network message type for this packet message.
	 * @param data
	 * The data.
	 */
	public PacketClientMsgProtobuf(EMsg eMsg, byte[] data) {
		msgType = eMsg;
		payload = data;
		final MsgHdrProtoBuf protobufHeader = new MsgHdrProtoBuf();
		// we need to pull out the job ids, so we deSerialize the protobuf header
		final BinaryReader ms = new BinaryReader(data);
		try {
			protobufHeader.deSerialize(ms);
		} catch (final IOException e) {
			uk.co.thomasc.steamkit.util.logging.DebugLog.writeLine("NEW_EX", "Exception: %s", e);
		}
		targetJobID = protobufHeader.proto.jobidTarget;
		sourceJobID = protobufHeader.proto.jobidSource;
	}

	/**
	 * Gets the underlying data that represents this client message.
	 */
	@Override
	public byte[] getData() {
		return payload;
	}

	/**
	 * The message type.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public EMsg getMsgType() {
		return this.msgType;
	}

	/**
	 * The message type.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setMsgType(final EMsg msgType) {
		this.msgType = msgType;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTargetJobID() {
		return this.targetJobID;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getSourceJobID() {
		return this.sourceJobID;
	}
}
