// Generated by delombok at Wed Jun 15 22:04:52 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamapps.callbacks;

import java.util.ArrayList;
import java.util.List;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver.CMsgClientAppInfoResponse;
import uk.co.thomasc.steamkit.steam3.handlers.steamapps.SteamApps;
import uk.co.thomasc.steamkit.steam3.handlers.steamapps.types.App;
import uk.co.thomasc.steamkit.steam3.handlers.steamapps.types.AppInfoStatus;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is received in response to calling
 * {@link SteamApps#getAppInfo(int)}.
 */
public final class AppInfoCallback extends CallbackMsg {
	/**
	 * Gets the list of apps this response contains.
	 */
	private final List<App> apps = new ArrayList<App>();
	/**
	 * Gets the number of apps pending in this response.
	 */
	private final int appsPending;

	public AppInfoCallback(CMsgClientAppInfoResponse msg) {
		for (final CMsgClientAppInfoResponse.App app : msg.apps) {
			apps.add(new App(app, AppInfoStatus.OK));
		}
		for (final Integer app : msg.appsUnknown) {
			apps.add(new App(app, AppInfoStatus.Unknown));
		}
		appsPending = msg.appsPending;
	}

	/**
	 * Gets the list of apps this response contains.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<App> getApps() {
		return this.apps;
	}

	/**
	 * Gets the number of apps pending in this response.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getAppsPending() {
		return this.appsPending;
	}
}
