// Generated by delombok at Wed Jun 15 22:04:52 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamapps.callbacks;

import java.util.ArrayList;
import java.util.List;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver.CMsgClientGameConnectTokens;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is fired when the client receives a list of game connect
 * tokens.
 */
public final class GameConnectTokensCallback extends CallbackMsg {
	/**
	 * Gets a count of tokens to keep.
	 */
	private final int tokensToKeep;
	/**
	 * Gets the list of tokens.
	 */
	private final List<byte[]> tokens = new ArrayList<byte[]>();

	public GameConnectTokensCallback(CMsgClientGameConnectTokens msg) {
		tokensToKeep = msg.maxTokensToKeep;
		for (final byte[] s : msg.tokens) {
			tokens.add(s);
		}
	}

	/**
	 * Gets a count of tokens to keep.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getTokensToKeep() {
		return this.tokensToKeep;
	}

	/**
	 * Gets the list of tokens.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<byte[]> getTokens() {
		return this.tokens;
	}
}
