// Generated by delombok at Wed Jun 15 22:04:52 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamapps.callbacks;

import java.util.ArrayList;
import java.util.List;
import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver.CMsgClientLicenseList;
import uk.co.thomasc.steamkit.base.generated.steamlanguage.EResult;
import uk.co.thomasc.steamkit.steam3.handlers.steamapps.types.License;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is fired during logon, informing the client of it's available
 * licenses.
 */
public final class LicenseListCallback extends CallbackMsg {
	/**
	 * Gets the result of the message.
	 */
	private final EResult result;
	/**
	 * Gets the license list.
	 */
	private final List<License> licenseList = new ArrayList<License>();

	public LicenseListCallback(CMsgClientLicenseList msg) {
		result = EResult.f(msg.eresult);
		for (final CMsgClientLicenseList.License l : msg.licenses) {
			licenseList.add(new License(l));
		}
	}

	/**
	 * Gets the result of the message.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public EResult getResult() {
		return this.result;
	}

	/**
	 * Gets the license list.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<License> getLicenseList() {
		return this.licenseList;
	}
}
