// Generated by delombok at Wed Jun 15 22:04:53 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamgameserver.callbacks;

import uk.co.thomasc.steamkit.base.generated.SteammessagesClientserver.CMsgGSStatusReply;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is fired when the game server receives a status reply.
 */
public final class StatusReplyCallback extends CallbackMsg {
	/**
	 * Gets a value indicating whether this game server is VAC secure.
	 */
	private final boolean isSecure;

	public StatusReplyCallback(CMsgGSStatusReply reply) {
		isSecure = reply.isSecure;
	}

	/**
	 * Gets a value indicating whether this game server is VAC secure.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isSecure() {
		return this.isSecure;
	}
}
