// Generated by delombok at Wed Jun 15 22:04:52 CDT 2016
package uk.co.thomasc.steamkit.steam3.handlers.steamfriends.callbacks;

import uk.co.thomasc.steamkit.base.generated.steamlanguage.EResult;
import uk.co.thomasc.steamkit.base.generated.steamlanguageinternal.msg.MsgClientSetIgnoreFriendResponse;
import uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg;

/**
 * This callback is fired in response to an attempt at ignoring a friend.
 */
public final class IgnoreFriendCallback extends CallbackMsg {
	/**
	 * Gets the result of ignoring a friend.
	 */
	private final EResult result;

	public IgnoreFriendCallback(MsgClientSetIgnoreFriendResponse response) {
		result = response.result;
	}

	/**
	 * Gets the result of ignoring a friend.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public EResult getResult() {
		return this.result;
	}
}
